version: '3.8'
services:
  app: &app
    build:
      context: ../..
      dockerfile: ops/dev/Dockerfile
      args:
        RUBY_VERSION: '2.6.3'
        PG_MAJOR: '12'
        NODE_MAJOR: '12'
        BUNDLER_VERSION: '2.1.4'
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    user: app
    volumes:
      - ../..:/home/app/web:cached
      - bundle:/home/app/bundle
      - node_modules:/home/app/web/node_modules
    env_file:
      - app_env
      - app_env.secrets
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - WEB_CONCURRENCY=1
      - EDITOR=vi
    depends_on:
      - postgres
      - redis

  rails:
    <<: *backend
    command: bin/rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:12.3
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
