:concurrency: 6
:queues:
  - default
  - mailers
  - newsletter
  - newsletters_opt_in
  - events
  - metrics

:schedule:
  CalculateAllMetrics:
    cron: '0 6,14,22 * * *'
    class: CalculateAllMetricsJob
  PreloadOpenData:
    cron: '0 17 * * *'
    class: PreloadOpenDataJob
  CheckPublishedInitiatives:
    cron: '0 8,16,23 * * *'
    class: CheckPublishedInitiatives
  CheckValidatingInitiatives:
    cron: '30 8,16,23 * * *'
    class: CheckValidatingInitiatives
  NotifyProgressInitiatives:
    cron: '45 8,16,23 * * *'
    class: NotifyProgressInitiatives
  CleanSessions:
    cron: '0 5 * * *'
    class: CleanSessions
